import { parse, printAstro } from '@versoly/ast';
import { plugins, getActivePlugins, getFilteredPlugins } from '@versoly/plugins';

import { kebabCaseToPascal, toKebabCase } from 'src/utils';
import { VersolyComponent, VersolyFile, VersolyPage } from 'src/types';

//  at ${new Date().toISOString()}
export const getAutoGeneratedStr = () => `// auto-generated by Versoly`;

const addDelimiter = (content: string) => {
  return content.startsWith('---') ? content : `---\n---\n${content}`;
};

const stripNewLinesFromStartEnd = (str: string) => {
  if (!str) {
    return '';
  }

  if (str.startsWith('\n')) {
    str = str.slice(1);
  }
  if (str.endsWith('\n')) {
    str = str.slice(0, -1);
  }
  return str;
};

const getSplitAstroContent = (content: string) => {
  content = addDelimiter(content);
  let astroStr = content.split('---').at(1);
  let jsxStr = content.split('---').at(-1);

  return {
    astroStr: stripNewLinesFromStartEnd(astroStr || ''),
    jsxStr: stripNewLinesFromStartEnd(jsxStr || ''),
  };
};

// const installedPlugins = fs.readdirSync(pluginsDir).map((p) => p.replace('.js', ''));

const getImportPluginsStr = (HTML: string) => {
  const activePlugins = getActivePlugins(HTML);

  let importPluginsStr = '';

  let pluginsList = getFilteredPlugins({ HTML, activePlugins });

  importPluginsStr += pluginsList.map(
    (p) => `
<script>
  import "@/scripts/plugins/${toKebabCase(p.name)}.js";
</script>`,
  );

  return importPluginsStr;
};

const generatePageMetadata = (page: VersolyPage) => {
  const metadata = {
    title: page.seo.title,
    description: page.seo.description,
    metaTags: page.metaTags,
    head: page.head,
    scripts: page.scripts,
    bodyProperties: page.bodyProperties,
  };
  // noindex comes from metaTags <meta name="robots" content="noindex">
  // canonical comes from metaTags { field: 'rel', value: 'canonical', content: 'https://www.example.com' }
  return `const metaData = ${JSON.stringify(metadata, null, 2)};`;
};

export const generatePage = async (page: VersolyPage, pagesDir: string) => {
  if (page.status !== 'publish' || page.collectionProperties) {
    return null;
  }

  const ast = parse(page.content);
  let content = await printAstro({ ast });

  let { astroStr, jsxStr } = getSplitAstroContent(content);

  content = [
    //
    `---`,
    getAutoGeneratedStr(),
    `import PageLayout from "@/layouts/PageLayout.astro";`,
    generatePageMetadata(page),
    astroStr,
    `---`,
    `<PageLayout {...metaData}>`,
    jsxStr,
    `</PageLayout>`,
    getImportPluginsStr(jsxStr),
  ]
    .filter(Boolean)
    .join('\n');

  return {
    type: 'page',
    path: [pagesDir, page.folderPath, page.slug === '' ? 'index' : page.slug].filter(Boolean).join('/'),
    content,
    plugins: getActivePlugins(jsxStr),
    extension: 'astro',
  } as VersolyFile & { content: string };
};

export const generateComponent = async (component: VersolyComponent, componentsDir: string) => {
  const { name, folderPath, properties } = component;

  const ast = parse(component.content);

  let content = await printAstro({
    ast,
    component: { properties },
  });

  let { astroStr, jsxStr } = getSplitAstroContent(content);

  content = [`---`, getAutoGeneratedStr(), astroStr, `---`, jsxStr, getImportPluginsStr(jsxStr)]
    .filter(Boolean)
    .join('\n');

  const path = [componentsDir, folderPath, kebabCaseToPascal(name)].filter(Boolean).join('/');

  return {
    type: 'component',
    path,
    content,
    plugins: getActivePlugins(jsxStr),
    extension: 'astro',
  } as VersolyFile & { content: string };
};
