// auto-generated by Versoly

export const $d = (
  rawDate: string | Date,
  options?: Intl.DateTimeFormatOptions,
  locale?: string,
) => {
  let date = new Date(rawDate);
  options = options || {
    year: "numeric",
    month: "long",
    day: "numeric",
  };
  locale = locale || "en-US";
  return new Intl.DateTimeFormat(locale, options).format(date);
};
          