// auto-generated by Versoly

export type MetaTags = Array<{
  field: string;
  value: string;
  content: string;
}>;

export type PageMetaProps = {
  favicon?: string;
  url?: string;
  title: string;
  description: string;
  metaTags: MetaTags;
  lang?: string;
  head?: string;
  scripts?: string;
  bodyProperties: {
    id?: string;
    className?: string;
    [key: string]: string | undefined;
  };
};

export type PageLayoutMetaProps = {
  site: {
    favicon?: string;
    title: string;
    description: string;
    metaTags: MetaTags;
  };
  obj: PageMetaProps;
};

export const metaTagsToString = ({ site, obj }: PageLayoutMetaProps) => {
  let { title, description, favicon } = {
    ...site,
    ...obj,
  };

  let metaTags = obj.metaTags || site.metaTags || [];
  let canonical = obj.url || "";

  metaTags.forEach(({ field, value, content }) => {
    if (field === "rel" && value === "canonical") {
      canonical = content;
      return;
    }
  });

  const defaultMetaTags = [
    // { field: 'rel', value: 'canonical', content: 'https://www.example.com' }
    { field: "property", value: "og:type", content: "website" },
    { field: "property", value: "og:url", content: canonical },
    { field: "property", value: "og:title", content: title },
    { field: "property", value: "og:description", content: description },
    //   value: "og:image",
    {
      field: "name",
      value: "twitter:card",
      content: "summary_large_image",
    },
    { field: "name", value: "twitter:url", content: canonical },
    { field: "name", value: "twitter:title", content: title },
    { field: "name", value: "twitter:description", content: description },
    //   value: "twitter:image",
  ].filter((tag) => tag.content);

  defaultMetaTags.forEach((tag) => {
    if (metaTags.find((t) => t.field === tag.field && t.value === tag.value)) {
      return;
    }

    metaTags.push(tag);
  });

  site.metaTags.forEach((tag) => {
    if (metaTags.find((t) => t.field === tag.field && t.value === tag.value)) {
      return;
    }
    metaTags.push(tag);
  });

  let imageMetaTag =
    metaTags.find((tag) => tag.value === "og:image") ||
    metaTags.find((tag) => tag.value === "twitter:image");

  let imageURL = imageMetaTag?.content || "";

  if (imageURL) {
    metaTags.push({ field: "property", value: "og:image", content: imageURL });
    metaTags.push({ field: "name", value: "twitter:image", content: imageURL });
  }

  let strList = [
    favicon && `<link rel="icon" href="${favicon}" />`,
    `<title>${title}</title>`,
    `<meta name="title" content="${title}" />`,
    `<meta name="description" content="${description}" />`,
    canonical && `<link rel="canonical" href="${canonical}" />`,
  ];

  metaTags.forEach((tag) => {
    if (tag.field === "rel" && tag.value === "canonical") {
      return;
    }
    strList.push(
      `<meta ${tag.field}="${tag.value}" content="${tag.content}" />`,
    );
  });

  console.log(strList);
  return strList.filter(Boolean).join("\n");
};
