// auto-generated by Versoly

window.vDelayed = {};
window.vLoadedDelayed = {};

window.vGetElementsByToggle = (toggleName) => {
  const query = '[data-toggle="' + toggleName + '"]';
  return [...document.querySelectorAll(query)];
};

window.vGetElementOptions = (elem) => {
  let options = {};

  try {
    if (elem.dataset.options) {
      options = elem.dataset.options.split("'").join('"');
      options = JSON.parse(options);
    }
  } catch (err) {
    console.log(err);
    options = {};
  }

  return options;
};
