// auto-generated by Versoly

var s = document.createElement("script");
s.src =
  "https://cdnjs.cloudflare.com/ajax/libs/vanilla-tilt/1.8.0/vanilla-tilt.js";
s.async = false;
document.body.appendChild(s);
s.onload = function () {
  window.vTilts = [];
  window.vGetElementsByToggle("tilt").forEach((tiltEle, index) => {
    const options = window.vGetElementOptions(tiltEle);
    VanillaTilt.init(tiltEle, options);
    tiltEle.setAttribute("data-tilt-index", index);
    window.vTilts.push(tiltEle);
  });
};
